mysite/contact/urls.py
from django.conf.urls import url

#import views as contact_views
from views import ContactFormView
urlpatterns = [
    #url(r'^$', contact_views.contact, name='contact'),
    url(r'^$', ContactFormView.as_view(), name='contact'),

]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from profiles import views as profiles_views
from photo import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', profiles_views.HomeTV.as_view(), name='home'),
    url(r'^about$', profiles_views.AboutTV.as_view(), name='about'),
    url(r'^profile/', profiles_views.userProfile, name='profile'),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

    #url(r'^$', views.home, name='home'),
]
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # static/static-only
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # static/media

mysite/photo/urls.py
from django.conf.urls import url
from photo.views import *

urlpatterns = [
	# Example: /
	url(r'^$',AlbumLV.as_view(), name='index'),

	# /album/, same as /
	url(r'^album/$', AlbumLV.as_view(), name='album_list'),

	# /album/10/
	url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),

	# /photo/10/
	url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),
]

mysite/profiles/urls.py
from django.conf.urls import url

from . import views
from .views import HomeTV, AboutTV

urlpatterns = [
    #url(r'^$', views.home, name='home'),
    #url(r'^$', HomeTV.as_view(), name='home'),
    #url(r'^about/$', AboutTV.as_view(), name='about'),
    #url(r'^$', HomeTV.as_view(), name='home'),

]

mysite/contact/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

mysite/photo/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.core.urlresolvers import reverse
from photo.fields import ThumbnailImageField
class Album(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField('One Line Dsecription', max_length=100, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))

class Photo(models.Model):
    album = models.ForeignKey(Album)
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('Photo Description', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

mysite/profiles/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class profile(models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField(default='description default text')

    def __unicode__(self):
        return self.name

mysite/contact/forms.py
from django import forms

class contactForm(forms.Form):
    name = forms.CharField(required=False, max_length=100, help_text='100 characters max.')
    email = forms.EmailField(required=True)
    comment = forms.CharField(required=True, widget=forms.Textarea)

mysite/contact/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render

# Create your views here.
from .forms import contactForm
from django.core.mail import send_mail
from django.conf import settings
#------- 함수로 구현한 contactForm 뷰
# def contact(request):
#     form = contactForm(request.POST or None)
#
#     if form.is_valid():
#         #print request.POST
#         #print form.cleaned_data['email']
#         name = form.cleaned_data['name']
#         comment = form.cleaned_data['comment']
#         subject = 'Message from MYSITE.com'
#         message = '%s\n\n from %s' %(comment, name)
#         emailFrom = form.cleaned_data['email']
#         emailTo = [settings.EMAIL_HOST_USER]
#         send_mail(subject, message, emailFrom, emailTo, fail_silently=True)
#
#     context = locals()
#     template = 'contact/contact.html'
#     return render(request, template, context)
from django.views.generic.edit import FormView
from .forms import contactForm
#------- 클래스로 구현한 contactForm 뷰
class ContactFormView(FormView):
    form_class = contactForm
    template_name = 'contact/contact.html'

    def form_valid(self,form):
        name = self.request.POST['name']
        comment = self.request.POST['comment']
        subject = 'Message from MYSITE.com'
        message = '%s\n\n from %s' % (comment, name)
        emailFrom = self.request.POST['email']
        emailTo = [settings.EMAIL_HOST_USER]

        send_mail(subject, message, emailFrom, emailTo, fail_silently=True)

        confirm_message = "Thanks for the message. We will get right back to you."

        context = {}
        #context['form'] = form
        context['sender'] = name
        context['email'] = emailFrom
        context['confirm_message'] = confirm_message
        return render(self.request, self.template_name, context)

mysite/photo/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView
from photo.models import Album, Photo

class AlbumLV(ListView):
	model = Album

class AlbumDV(DetailView):
	model = Album

class PhotoDV(DetailView):
	model = Photo

mysite/profiles/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
def home(request):
    context = locals()
    template = 'profiles/home.html'
    return render(request, template, context)

from django.views.generic.base import TemplateView
#--- TemplateView
class HomeTV(TemplateView):
    template_name = 'profiles/home.html'

class AboutTV(TemplateView):
    template_name = 'profiles/about.html'

@login_required
def userProfile(request):
    user = request.user
    context = {'user': user}
    template = 'profiles/profile.html'
    return render(request, template, context)

mysite/contact/templates/contact/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
<div class="col-sm-6 col-sm-offset-3">
{% if form %}
    <h1> Contact </h1>
    <form method='POST' action=""> {% csrf_token %}
        {{ form|crispy }}
        <input type='submit' value='submit form' class='btn btn-default' />
    </form>
{% endif %}

{% if confirm_message %}
    <h1> Thanks </h1>
    <p><font color="blue">{{ sender }}({{ email }})</font> 님의 글을 잘 전달하였습니다.</p>
    <p> {{ confirm_message }} </p>
{% endif %}
</div>


</div>
{% endblock %}

mysite/photo/templates/photo/album_detail.html
{% extends "base.html" %}

{% block title %}album_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}<link rel='stylesheet' href="{% static 'css/photo.css' %}" />{% endblock %}

{% block content %}

<div id="content">

<h2 style="display:inline">{{ object.name }}</h2>
&emsp;<b><i>{{ object.description }}</i></b>

<hr />

<div class="album-detail">
{% for photo in object.photo_set.all %}
	<div class="album-detail-photo">
	<a href="{{ photo.get_absolute_url }}">
	<img class="thumbnail" src="{{ photo.image.thumb_url }}" /></a>
	<li>{{ photo.title }}</li>
	<li>{{ photo.upload_date|date:"Y-m-d"}}</li>
	</div>
{% endfor %}
</div>

</div>

{% endblock %}

mysite/photo/templates/photo/album_list.html
{% extends "base.html" %}

{% block title %}album_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}<link rel='stylesheet' href="{% static 'css/photo.css' %}" />{% endblock %}

{% block content %}

<div id="content">

{% for item in object_list %}
	<div class="clear_float">
		<h2 style="display:inline"><a href="{% url 'photo:album_detail' item.id %}">{{ item.name }}</a></h2>
		&emsp;<b><i>{{ item.description }}</i></b>
	</div>

	<hr />

	<div class="album-list">
	{% for photo in item.photo_set.all|slice:":5" %}
		<div class="album-list-photo">
		<a href="{{ photo.get_absolute_url }}"><img class="thumbnail" src="{{ photo.image.thumb_url }}" /></a>
		</div>
	{% endfor %}
	</div>

{% endfor %}

</div>
{% endblock %}

mysite/photo/templates/photo/photo_detail.html
{% extends "base.html" %}

{% block title %}album_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}<link rel='stylesheet' href="{% static 'css/photo.css' %}" />{% endblock %}

{% block content %}

<div id="content">

<h2>{{ object.title }}</h2>

<table class="photo-detail">
<tr>
	<td>
	<a href="{{ object.image.url }}">
	<img style="max-width:100%" src="{{ object.image.url }}" />
	</a>
	</td>

	<td>
	<ul>
	<li>Photo Description</li>
	{% if object.description %}<p>{{ object.description|linebreaks }}</p>
	{% else %}<p>(blank)</p>{% endif %}
	<li>Date Uploaded</li>
	<p>{{ object.upload_date }}</p>
	<li>Album Name</li>
	<p><a href="{% url 'photo:album_detail' object.album.id %}">
	{{ object.album.name }}</a></p>
	</ul>
	</td>
</tr>
</table>
<br/>
	<div>
		{% load disqus_tags %}
		{% disqus_show_comments %}
	</div>
</div>

{% endblock %}

mysite/profiles/templates/profiles/about.html
{% extends 'base.html' %}

{% block content %}
<h1> hello about </h1>
{% endblock %}

mysite/profiles/templates/profiles/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block styles %}
<style>
    .jumbotron {
        text-align: center;
    }
</style>
{% endblock %}

{% block jumbotron %}
      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>Theme example</h1>
        <p>This is a template showcasing the optional theme stylesheet included in Bootstrap. Use it as a starting point to create something more unique by building on or modifying it.</p>
      </div>
{% endblock %}

{% block content %}
<div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-md-4">
            <a href="#"><img src="{% static 'img/home.png' %}" class="img-responsive" /></a>
            <p></p>
       </div>
        <div class="col-md-4">
            {% if request.user.is_authenticated %}
            <h3>Hello {{ request.user }}</h3>
            {% else %}
            <form class="login" method="POST" action="{% url 'account_login' %}"> {% csrf_token %}

            <div id="div_id_login" class="form-group"> <label for="id_login" class="control-label  requiredField">
                            Login<span class="asteriskField">*</span> </label> <div class="controls "> <input autofocus="autofocus" class="textinput textInput form-control" id="id_login" name="login" placeholder="Username or e-mail" type="text" required=""> </div> </div> <div id="div_id_password" class="form-group"> <label for="id_password" class="control-label  requiredField">
                            Password<span class="asteriskField">*</span> </label> <div class="controls "> <input class="textinput textInput form-control" id="id_password" name="password" placeholder="Password" type="password" required=""> </div> </div> <div class="form-group"> <div id="div_id_remember" class="checkbox"> <label for="id_remember" class=""> <input class="checkboxinput" id="id_remember" name="remember" type="checkbox">
                                Remember Me
                            </label> </div> </div>


              <a class="btn btn-link button secondaryAction" href="{% url 'account_reset_password' %}">Forgot Password?</a>
              <button class="btn btn-link secondaryAction" href="{% url 'account_signup' %}">Signup</button>
              <button class="btn btn-default primaryAction" type="submit">Sign In</button>
            </form>
            {% endif %}
        </div>
      </div>
{% endblock %}

mysite/profiles/templates/profiles/profile.html
{% extends 'base.html' %}

{% block content %}
{{ user.username }}
{{ user.email }}
{% endblock %}

mysite/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Theme Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet">
    <link rel='stylesheet' href="{% static 'css/main.css' %}" />
    {% block extrastyle %}{% endblock %}
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    {% include 'navbar.html' %}

    <div class="container theme-showcase" role="main">

      {% block jumbotron %}
      {% endblock %}

      {% block content %}
      {% endblock %}
      {% block styles %}
      {% endblock %}


    </div> <!-- /container -->




    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'javascript/bootstrap.min.js' %}"></script>
    <script src="{% static 'javascript/docs.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

mysite/templates/navbar.html
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">*** SkinMon ***</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% url 'home' as home %}
            {% url 'about' as about %}
            {% url 'photo:album_list' as album %}
            {% url 'contact:contact' as contact %}
            <li {% if request.path == home %} class="active" {% endif %}><a href="{% url 'home' %}">Home</a></li>
            <li {% if request.path == about %} class="active" {% endif %}><a href="{% url 'about' %}">About</a></li>
            <li {% if request.path == album %} class="active" {% endif %}><a href="{% url 'photo:album_list' %}">LaserDB</a></li>
            <li {% if request.path == contact %} class="active"{% endif %}><a href="{% url 'contact:contact' %}">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                {% if not request.user.is_authenticated %}
                <li><a href="{% url 'account_login' %}">Login</a></li>
                <li><a href="{% url 'account_signup' %}">Signup</a></li>
                {% else %}
                <li><a href="{% url 'account_logout' %}">Logout</a></li>
                {% endif %}
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>